# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container to /app
WORKDIR /app

# Add only requirements.txt and tsrc-dev.py into the container at /app
ADD requirements.txt tsrc-dev.py turbosrc.config /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run script.py when the container launches
CMD ["python", "tsrc-dev.py"]