#!/bin/bash

# Global variables
github_user=""
github_key=""

# Function to get GithubName from turbosrc.config
get_github_user() {
    github_user=$(jq -r '.GithubName' ./turbosrc.config)
}

# Function to get GithubApiToken from turbosrc.config
get_github_key() {
    github_key=$(jq -r '.GithubApiToken' ./turbosrc.config)
}

# Function to push to GitHub using credentials
git_push_with_credentials() {
    # Navigate to the tsrc-demo-conflict directory
    cd ./tsrc-demo-conflict

    # Set the remote URL
    git remote set-url origin https://github.com/$github_user/tsrc-demo-conflict.git

    # Temporarily configure Git to use the GitHub API key for this session
    GIT_ASKPASS="echo $github_key" git -c credential.helper= -c user.name="$github_user" -c user.password="$github_key" push origin master

    # Return to the original directory
    cd -
}

# Execute functions
get_github_user
get_github_key
git_push_with_credentials
